name: deploy api
env:
  HOST: ${{ secrets.LIGHTSAIL_HOST }}
  REGION: ${{ secrets.LIGHTSAIL_REGION }}
  USERNAME: ${{ secrets.LIGHTSAIL_USER }}
  SSH_KEY: ${{ secrets.LIGHTSAIL_SECRET_KEY }}
  API_DIRECTORY: ${{ secrets.API_DIRECTORY }}
  INSTANCE_NAME: ${{ secrets.INSTANCE_NAME }}
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install node v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: pull source code
        uses: actions/checkout@v4

      - name: package install
        run: npm install

      - name: build project
        run: npm rum build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy latest commit
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{env.USERNAME}}
          key: ${{ env.SSH_KEY }}
          script: |
            cd ${{ env.API_DIRECTORY }}
            git pull origin master
            npm install
            npm run build
            pm2 restart ${{ env.INSTANCE_NAME }}
